# Generated by Django 5.1.6 on 2025-03-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
        ('property', '0002_remove_property_reservation_reservation_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_lead', to='leads.lead'),
        ),
    ]
